### PR TITLE
ENH: Add as action

### PR DESCRIPTION
**Pull request by larsoner**
I would like to be able to do in my actions:
```
    - uses: pyvista/gl-ci-helpers@master
```
and have Qt+OpenGL usable on every OS. This is an attempt at making this happen.

Note I add a new `setup_xvfb.sh` based on what we use in MNE-Python to ensure that all system libraries are available on Ubuntu for Xvfb.

### CODE REVIEW

**Comment by banesullivan** [comment]
Does https://github.com/pyvista/setup-headless-display-action work for you?

We aren't using this repo anymore, so whatever you want to do here is fine by me

**Comment by larsoner** [comment]
Ahh yes I should probably just work from there. It's just missing the Qt libraries, but I can add those as a boolean option over there!

**Comment by banesullivan** [comment]
I'm inclined for the Qt stuff to maybe be its own action rather than bundling into the headless display action (to keep scope focused and targeted)

**Comment by banesullivan** [comment]
I just don't want to be left responsible for maintaining any Qt stuff 😄

**Pull request closed without merging**
