### PR TITLE
MAINT: Add CIs

### PR DESCRIPTION
**Pull request by larsoner**
- [x] ~~See if it actually works for AppVeyor (should) and Azure (should not)~~
- [x] Make it work for AppVeyor and Azure using `$env:` or some other method (verified in https://github.com/LABSN/expyfun/pull/376)
- [x] Enable AppVeyor and Azure on their sites (@banesullivan)

### CODE REVIEW

**Comment by banesullivan** [comment]
Just enabled Appeyor

**Comment by larsoner** [comment]
FYI to set up you can add Azure as an app for the vtkiorg organization, on the Azure site have it set up the basic repo (it will make a commit) then I can change it here

**Comment by banesullivan** [comment]
Not sure what I need to do on Azure to make that happen...

**Comment by larsoner** [comment]
Look how easy it is!

- Go here https://github.com/marketplace/azure-pipelines
- Click the green button "Set up new plan"
- At the bottom of the page, change account from `banesullivan` to `vtkiorg`
- Click the green button "install it for free"
- Click "complete order and begin installation"
- Click another green button to install access to all repos (or not, if you wan to restrict)
- Sign into Azure
- Select vtkiorg, projct `gl-ci-helpers` (for now), click continue
- Click on the GitHub repo
- Starter pipeline
- Save and run

**Comment by banesullivan** [comment]
Thanks for the step-by-step!

> Look how easy it is!

Very Microsoft-y: going through menu after menu after menu

**Comment by banesullivan** [comment]
Do you want to resolve the conflict with the script you added?

**Comment by larsoner** [comment]
All good, @banesullivan feel free to merge

**Comment by banesullivan** [comment]
Thanks for all your help here. @larsoner!

**Pull request merged**
